CXX = g++
CXXFLAGS = -Wall

lab6: lab6.cpp Valorant.o
	$(CXX) $(CXXFLAGS) lab6.cpp Valorant.o -o lab6

Valorant.o: Valorant.h Valorant.cpp
	$(CXX) $(CXXFLAGS) -c Valorant.cpp

run:
	./lab6

clean:
	rm *~
